import type { ReportDatasetManifest } from "./types.ts";

/**
 * PO11 metadata only.  Phase 4 will add the separate authoritative adapter
 * that maps existing PO11 planning decisions to these safe field keys.
 */
export const PO11_PLANNING_ALERT_REPORT_DATASET: ReportDatasetManifest = {
  dataset_key: "planning_alert",
  label: "Planning Alert",
  description: "Procurement-planning decision and alert output.",
  page: {
    tx_code: "PO11",
    resource_code: "PROC_PLANNING_VIEW",
  },
  surface_keys: ["planning_dashboard", "report_view"],
  empty_output_is_meaningful: true,
  intended_row_grain:
    "One planning item group decision row, or one standalone material decision row.",
  row_identity_field_keys: ["decision_type", "decision_key"],
  default_display_field_keys: [
    "planning_status",
    "decision_type",
    "material_type",
    "material_code",
    "material_name",
    "group_name",
    "source_sloc_group",
    "monthly_requirement_qty",
    "available_stock_qty",
    "safety_stock_qty",
    "replenishment_stock_qty",
    "trn_stock_qty",
    "gate_entry_stock_qty",
    "qa_stock_qty",
    "uom",
  ],
  fields: [
    {
      field_key: "planning_status",
      label: "Planning Status",
      data_type: "ENUM",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "IN", "NOT_IN"],
      format_kind: "ENUM_LABEL",
      enum_values: [
        { value: "CRITICAL", label: "Critical" },
        { value: "REPLENISH", label: "Replenish" },
        { value: "NORMAL", label: "Normal" },
      ],
    },
    {
      field_key: "decision_type",
      label: "Decision Type",
      data_type: "ENUM",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "IN", "NOT_IN"],
      format_kind: "ENUM_LABEL",
      enum_values: [
        { value: "ITEM_GROUP", label: "Planning Item Group" },
        { value: "STANDALONE_MATERIAL", label: "Standalone Material" },
      ],
    },
    {
      field_key: "decision_key",
      label: "Decision Key",
      data_type: "STRING",
      displayable: false,
      conditionable: false,
      allowed_operators: [],
      format_kind: "TEXT",
    },
    {
      field_key: "material_type",
      label: "Material Type",
      data_type: "STRING",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "IN", "NOT_IN"],
      format_kind: "TEXT",
    },
    {
      field_key: "material_code",
      label: "Material Code",
      data_type: "STRING",
      displayable: true,
      conditionable: true,
      allowed_operators: [
        "EQ",
        "NE",
        "IN",
        "NOT_IN",
        "IS_EMPTY",
        "IS_NOT_EMPTY",
      ],
      format_kind: "TEXT",
    },
    {
      field_key: "material_name",
      label: "Material Name",
      data_type: "STRING",
      displayable: true,
      conditionable: true,
      allowed_operators: [
        "EQ",
        "NE",
        "IN",
        "NOT_IN",
        "IS_EMPTY",
        "IS_NOT_EMPTY",
      ],
      format_kind: "TEXT",
    },
    {
      field_key: "group_name",
      label: "Planning Item Group",
      data_type: "STRING",
      displayable: true,
      conditionable: true,
      allowed_operators: [
        "EQ",
        "NE",
        "IN",
        "NOT_IN",
        "IS_EMPTY",
        "IS_NOT_EMPTY",
      ],
      format_kind: "TEXT",
    },
    {
      field_key: "source_sloc_group",
      label: "Source SLOC Group",
      data_type: "STRING",
      displayable: true,
      conditionable: true,
      allowed_operators: [
        "EQ",
        "NE",
        "IN",
        "NOT_IN",
        "IS_EMPTY",
        "IS_NOT_EMPTY",
      ],
      format_kind: "TEXT",
    },
    {
      field_key: "monthly_requirement_qty",
      label: "Monthly Requirement Quantity",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "QUANTITY",
    },
    {
      field_key: "available_stock_qty",
      label: "Available Stock Quantity",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "QUANTITY",
    },
    {
      field_key: "safety_stock_qty",
      label: "Safety Stock Quantity",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "QUANTITY",
    },
    {
      field_key: "replenishment_stock_qty",
      label: "Replenishment Stock Quantity",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "QUANTITY",
    },
    {
      field_key: "trn_stock_qty",
      label: "TRN Stock Quantity",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "QUANTITY",
    },
    {
      field_key: "gate_entry_stock_qty",
      label: "Gate Entry Stock Quantity",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "QUANTITY",
    },
    {
      field_key: "qa_stock_qty",
      label: "QA Stock Quantity",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "QUANTITY",
    },
    {
      field_key: "safety_days",
      label: "Safety Days",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "DECIMAL",
    },
    {
      field_key: "processing_days",
      label: "Processing Days",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "DECIMAL",
    },
    {
      field_key: "lead_time_days",
      label: "Lead Time Days",
      data_type: "NUMBER",
      displayable: true,
      conditionable: true,
      allowed_operators: ["EQ", "NE", "GT", "GTE", "LT", "LTE", "BETWEEN"],
      format_kind: "DECIMAL",
    },
    {
      field_key: "uom",
      label: "UOM",
      data_type: "STRING",
      displayable: true,
      conditionable: true,
      allowed_operators: [
        "EQ",
        "NE",
        "IN",
        "NOT_IN",
        "IS_EMPTY",
        "IS_NOT_EMPTY",
      ],
      format_kind: "TEXT",
    },
  ],
};
