/*
 * File-ID: 9.3-H1
 * File-Path: supabase/functions/api/_core/admin/group/create_group.handler.ts
 * Gate: 9
 * Phase: 9
 * Domain: MASTER
 * Purpose: Create Group (SA-only)
 * Authority: Backend
 */

import { getServiceRoleClientWithContext } from "../../../_shared/serviceRoleClient.ts";
import type { ContextResolution } from "../../../_pipeline/context.ts";
import { okResponse, errorResponse } from "../../../_core/response.ts";

// --------------------------------------------------
// Admin guard (mirrors Company handler)
// --------------------------------------------------
function assertAdmin(ctx: { context: ContextResolution }): void {
  if (
    ctx.context.status !== "RESOLVED" ||
    ctx.context.isAdmin !== true
  ) {
    throw new Error("ADMIN_ONLY");
  }
}

// --------------------------------------------------
// Input contract
// --------------------------------------------------
type CreateGroupInput = {
  name?: string;
};

// --------------------------------------------------
// Handler
// --------------------------------------------------
export async function createGroupHandler(
  req: Request,
  ctx: { context: ContextResolution; request_id: string }
): Promise<Response> {
  try {
    // 1️⃣ Admin guard
    assertAdmin(ctx);

    // 2️⃣ Parse + validate input
    const body = (await req.json()) as CreateGroupInput;

    const name = body.name?.trim();
    if (!name || name.length < 3) {
      return errorResponse(
        "INVALID_GROUP_NAME",
        "invalid group name",
        ctx.request_id
      );
    }

    // 3️⃣ Insert (group_code auto-generated by DB)
    const db = getServiceRoleClientWithContext(ctx.context);

    const { data, error } = await db
      .schema("erp_master").from("groups")
      .insert({
        name,
        state: "ACTIVE",
      })
      .select("id, group_code, name, state")
      .single();

    if (error) {
      return errorResponse(
        "GROUP_CREATE_FAILED",
        "group create failed",
        ctx.request_id
      );
    }

    // 4️⃣ Success
    return okResponse(
      {
        group: {
          id: data.id,
          group_code: data.group_code,
          name: data.name,
          state: data.state,
        },
      },
      ctx.request_id
    );
  } catch (err) {
    return errorResponse(
      (err as Error).message || "GROUP_CREATE_EXCEPTION",
      "group create exception",
      ctx.request_id
    );
  }
}
