/*
 * File-ID: ID-6.3.5
 * File-Path: supabase/functions/api/_core/admin/company/create_company.handler.ts
 * Gate: 6
 * Phase: 6
 * Domain: MASTER
 * Purpose: Create company with optional GST autofill (cache-first, cost-safe)
 * Authority: Backend (SA / GA only)
 */

import { getServiceRoleClientWithContext } from "../../../_shared/serviceRoleClient.ts";
import type { ContextResolution } from "../../../_pipeline/context.ts";
import { resolveGstProfile } from "../../../_shared/gst_resolver.ts";
import { okResponse, errorResponse } from "../../../_core/response.ts";

// ------------------------------------------------------------------
// Minimal admin context (Gate-6 contract)
// ------------------------------------------------------------------
type AdminContext = {
  context: ContextResolution;
  request_id: string;
};

function assertAdmin(ctx: AdminContext): void {
  if (
    ctx.context.status !== "RESOLVED" ||
    ctx.context.isAdmin !== true
  ) {
    throw new Error("ADMIN_ONLY");
  }
}

// ------------------------------------------------------------------
// Input contract
// ------------------------------------------------------------------
type CreateCompanyInput = {
  company_name?: string;
  gst_number?: string;
};

// ------------------------------------------------------------------
// Handler
// ------------------------------------------------------------------
export async function createCompanyHandler(
  req: Request,
  ctx: AdminContext
): Promise<Response> {
  try {
    // 1️⃣ Admin guard
    assertAdmin(ctx);

    // 2️⃣ Parse input
    const body = (await req.json()) as CreateCompanyInput;

    const gst = body.gst_number
      ? body.gst_number.trim().toUpperCase()
      : null;

    // 3️⃣ Resolve GST (cache → Applyflow → cache)
    const gstProfile = gst
      ? await resolveGstProfile(gst)
      : null;

    // 4️⃣ Determine company name (GST autofill preferred)
    const companyName =
      gstProfile?.legal_name ??
      body.company_name?.trim();

    if (!companyName) {
      return errorResponse(
        "COMPANY_NAME_REQUIRED",
        "company name required",
        ctx.request_id
      );
    }

    // 5️⃣ Insert company (company_code auto-generated by DB)
    const db = getServiceRoleClientWithContext(ctx.context);

const { data, error } = await db
  .from("erp_master.companies")
  .insert({
    company_name: companyName,
    gst_number: gst,
  })
  .select()
  .single();

    if (error) {
      return errorResponse(
        "COMPANY_CREATE_FAILED",
        "company create failed",
        ctx.request_id
      );
    }

    // 6️⃣ Success
    return okResponse(
      {
        company: {
          company_code: data.company_code,
          company_name: data.company_name,
          gst_number: data.gst_number,
        },
      },
      ctx.request_id
    );
  } catch (err) {
    return errorResponse(
      (err as Error).message || "COMPANY_CREATE_EXCEPTION",
      "company create exception",
      ctx.request_id
    );
  }
}
