/*
 * File-ID: 13.2.2
 * File-Path: supabase/migrations/20260511021000_gate13_2_13_2_2_create_purchase_order.sql
 * Gate: 13.2
 * Phase: 13
 * Domain: PROCUREMENT
 * Purpose: Purchase Order header and lines - full L2 field set including Incoterms, Freight Term, LC Required, Rebate, Indent flags.
 * Authority: Backend
 */

BEGIN;

-- Purchase Order Header
CREATE TABLE IF NOT EXISTS erp_procurement.purchase_order (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- PO number: Company + Section prefix/suffix format (Section 33 / Section 99)
  -- Generated by handler using company-specific number series. Stored here.
  po_number               text NOT NULL UNIQUE,

  po_date                 date NOT NULL,
  -- system_created_at always set to now() - user po_date for backdating
  system_created_at       timestamptz NOT NULL DEFAULT now(),

  -- Cross-schema references - plain uuid, NO FK
  company_id              uuid NOT NULL,   -- → erp_master.companies
  plant_id                uuid NULL,       -- → erp_master.projects (destination plant, if known at PO)
  vendor_id               uuid NOT NULL,   -- → erp_master.vendor_master

  -- DOMESTIC | IMPORT
  vendor_type             text NOT NULL
    CHECK (vendor_type IN ('DOMESTIC', 'IMPORT')),

  -- Import POs: dynamic last-used Incoterm (Section 87.2)
  -- Domestic POs: NULL (not applicable)
  incoterm                text NULL,

  -- Freight Terms (Section 87.9) - mandatory on all POs
  -- FOR = vendor delivers to plant (no freight entry)
  -- FREIGHT_SEPARATE = buyer pays freight
  freight_term            text NOT NULL
    CHECK (freight_term IN ('FOR', 'FREIGHT_SEPARATE')),

  -- Payment Terms reference → erp_master.payment_terms_master(id)
  -- Plain UUID: cross-schema reference, no FK
  payment_term_id         uuid NOT NULL,

  -- LC Required: auto-derived when payment_method = LC on payment term
  -- Carries into CSN tracker
  lc_required             boolean NOT NULL DEFAULT false,

  -- Delivery Type (Section 91.1): drives CSN type
  -- STANDARD → IMPORT or DOMESTIC CSN
  -- BULK / TANKER → BULK CSN (weighment-based)
  delivery_type           text NOT NULL DEFAULT 'STANDARD'
    CHECK (delivery_type IN ('STANDARD', 'BULK', 'TANKER')),

  -- Rebate flag (Section 90.3) - carries to CSN
  has_rebate              boolean NOT NULL DEFAULT false,
  rebate_remarks          text NULL,

  -- Indent Required flag (Section 90.4) - inherited from vendor_master.indent_number_required
  -- Overridable per PO by Procurement
  indent_required         boolean NOT NULL DEFAULT false,

  -- Expected delivery date (for planning reference)
  expected_delivery_date  date NULL,

  -- PO Status flow
  -- DRAFT → PENDING_APPROVAL → APPROVED → CONFIRMED → CLOSED | CANCELLED
  status                  text NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'CONFIRMED', 'CLOSED', 'CANCELLED')),

  -- Cancellation
  cancellation_reason     text NULL,
  cancelled_at            timestamptz NULL,
  cancelled_by            uuid NULL,

  -- PO auto-mail: sent on CONFIRMED status
  po_mail_sent_at         timestamptz NULL,

  remarks                 text NULL,

  -- Audit
  created_by              uuid NOT NULL,
  created_at              timestamptz NOT NULL DEFAULT now(),
  approved_by             uuid NULL,
  approved_at             timestamptz NULL,
  last_updated_at         timestamptz NULL,
  last_updated_by         uuid NULL
);

COMMENT ON TABLE erp_procurement.purchase_order IS
'Purchase Order header. One PO per company. No cross-company PO. PO number uses company+section prefix/suffix format. CSN auto-created per line on CONFIRMED status. Cancellation: no approval, reason mandatory, zero-receipt condition.';

COMMENT ON COLUMN erp_procurement.purchase_order.lc_required IS
'Auto-set by handler when payment_term.payment_method = LC. Carries into CSN LC tracking section.';

COMMENT ON COLUMN erp_procurement.purchase_order.delivery_type IS
'STANDARD = regular CSN tracking. BULK/TANKER = BULK CSN (weighment-based, simplified tracking, multiple GEs per CSN).';

-- Purchase Order Lines
CREATE TABLE IF NOT EXISTS erp_procurement.purchase_order_line (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Intra-schema FK - purchase_order is in erp_procurement
  po_id                   uuid NOT NULL
    REFERENCES erp_procurement.purchase_order(id)
    ON DELETE RESTRICT,

  line_number             int NOT NULL,

  -- Cross-schema references - plain uuid, NO FK
  material_id             uuid NOT NULL,   -- → erp_master.material_master
  cost_center_id          uuid NOT NULL,   -- → erp_master.cost_center_master (Section 87.3 - mandatory)

  -- Receiving storage location - plain uuid, NO FK (cross-schema to erp_inventory)
  receiving_location_id   uuid NULL,       -- → erp_inventory.storage_location_master

  -- vendor_material_info_id: Approved Source List check reference
  -- Plain UUID - cross-schema to erp_master
  vendor_material_info_id uuid NOT NULL,   -- → erp_master.vendor_material_info

  ordered_qty             numeric(20, 6) NOT NULL CHECK (ordered_qty > 0),

  -- UOM in which PO is raised (from vendor_material_info.po_uom_code)
  po_uom_code             text NOT NULL,

  -- ordered_qty in base UOM - NULL when variable_conversion = true (actual weight known at GRN only)
  -- Section 87 Rule 5 from original Gate-13 spec
  ordered_qty_base_uom    numeric(20, 6) NULL,

  -- Rate in PO currency
  unit_rate               numeric(20, 4) NOT NULL CHECK (unit_rate > 0),

  -- Total value = ordered_qty × unit_rate
  total_value             numeric(20, 4) NOT NULL,

  -- Open qty: reduced by GRN. Starts = ordered_qty
  open_qty                numeric(20, 6) NOT NULL,

  -- Status per line
  -- OPEN → PARTIALLY_RECEIVED → FULLY_RECEIVED | KNOCKED_OFF | CANCELLED
  line_status             text NOT NULL DEFAULT 'OPEN'
    CHECK (line_status IN ('OPEN', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'KNOCKED_OFF', 'CANCELLED')),

  knock_off_reason        text NULL,
  knocked_off_at          timestamptz NULL,
  knocked_off_by          uuid NULL,

  remarks                 text NULL,

  created_at              timestamptz NOT NULL DEFAULT now(),
  last_updated_at         timestamptz NULL,

  UNIQUE (po_id, line_number)
);

COMMENT ON TABLE erp_procurement.purchase_order_line IS
'PO line. cost_center_id is mandatory per line (no auto-populate - same material goes to different cost centers). vendor_material_info_id must reference an ACTIVE ASL record for this vendor+material.';

COMMENT ON COLUMN erp_procurement.purchase_order_line.ordered_qty_base_uom IS
'NULL when variable_conversion = true on the vendor_material_info record - actual weight is only known at GRN time.';

COMMIT;
