/*
 * File-ID: 12.2
 * File-Path: supabase/migrations/20260509121000_gate12_12_2_create_material_master.sql
 * Gate: 12
 * Phase: 12
 * Domain: MASTER
 * Purpose: Create the core material master table with identity, UOM, QA, batch, and production fields.
 * Authority: Backend
 */

BEGIN;

CREATE TABLE IF NOT EXISTS erp_master.material_master (
  id                              uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- IDENTITY
  -- System-generated. Format: RM-00001, PM-00001, INT-00001, FG-00001
  -- Generated by application layer using per-type sequence. NEVER editable.
  pace_code                       text NOT NULL UNIQUE,

  -- Optional legacy/vendor code. Editable. Searchable.
  external_code                   text NULL,

  material_name                   text NOT NULL,
  short_name                      text NOT NULL,

  -- RM | PM | INT | FG | TRA | CONS
  material_type                   text NOT NULL
    CHECK (material_type IN ('RM', 'PM', 'INT', 'FG', 'TRA', 'CONS')),

  -- Grouping for reporting. Free text or future FK to a group master.
  material_group                  text NULL,

  description                     text NULL,
  specification                   text NULL,

  -- UOM
  -- Stock ledger always stores in base_uom
  base_uom_code                   text NOT NULL
    REFERENCES erp_master.uom_master(code)
    ON DELETE RESTRICT,

  purchase_uom_code               text NOT NULL
    REFERENCES erp_master.uom_master(code)
    ON DELETE RESTRICT,

  issue_uom_code                  text NOT NULL
    REFERENCES erp_master.uom_master(code)
    ON DELETE RESTRICT,

  -- FG-SPECIFIC
  -- Only populated for material_type = 'FG'
  shade_code                      text NULL,
  pack_code                       text NULL,
  -- Concatenation of shade_code + pack_code - application layer sets this
  external_sku                    text NULL,

  -- GST / COMPLIANCE
  hsn_code                        text NULL,

  -- PROCUREMENT / PLANNING
  -- EXTERNAL | IN_HOUSE | BOTH
  procurement_type                text NOT NULL DEFAULT 'EXTERNAL'
    CHECK (procurement_type IN ('EXTERNAL', 'IN_HOUSE', 'BOTH')),

  -- IMPORT | DOMESTIC | BOTH - affects costing context
  import_domestic_flag            text NOT NULL DEFAULT 'DOMESTIC'
    CHECK (import_domestic_flag IN ('IMPORT', 'DOMESTIC', 'BOTH')),

  -- BATCH / TRACEABILITY
  batch_tracking_required         boolean NOT NULL DEFAULT false,
  fifo_tracking_enabled           boolean NOT NULL DEFAULT false,
  expiry_tracking_enabled         boolean NOT NULL DEFAULT false,

  -- Shelf life in days. NULL = no expiry.
  shelf_life_days                 int NULL CHECK (shelf_life_days > 0),

  -- Minimum remaining shelf life (days) required at time of GRN
  min_shelf_life_at_grn_days      int NULL CHECK (min_shelf_life_at_grn_days >= 0),

  -- QA
  qa_required_on_inward           boolean NOT NULL DEFAULT true,
  qa_required_on_fg               boolean NOT NULL DEFAULT false,

  -- VALUATION
  -- Phase-1: WEIGHTED_AVERAGE only. DIRECT_BATCH_COST is Phase-2.
  valuation_method                text NOT NULL DEFAULT 'WEIGHTED_AVERAGE'
    CHECK (valuation_method IN ('WEIGHTED_AVERAGE', 'DIRECT_BATCH_COST')),

  valuation_class                 text NULL,

  -- PRODUCTION (FG / INT only)
  -- FIXED_BOM | ADMIX_STROKE | HYBRID | NULL (for RM/PM)
  production_mode                 text NULL
    CHECK (production_mode IN ('FIXED_BOM', 'ADMIX_STROKE', 'HYBRID')),

  bom_exists                      boolean NOT NULL DEFAULT false,

  -- Delivery tolerance - applies to Process Order / Packing Order
  delivery_tolerance_enabled      boolean NOT NULL DEFAULT false,
  under_delivery_tolerance_pct    numeric(5, 2) NULL CHECK (under_delivery_tolerance_pct >= 0),
  over_delivery_tolerance_pct     numeric(5, 2) NULL CHECK (over_delivery_tolerance_pct >= 0),

  -- STATUS
  -- DRAFT -> PENDING_APPROVAL -> ACTIVE -> INACTIVE | BLOCKED
  status                          text NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT', 'PENDING_APPROVAL', 'ACTIVE', 'INACTIVE', 'BLOCKED')),

  -- AUDIT
  created_at                      timestamptz NOT NULL DEFAULT now(),
  created_by                      uuid NOT NULL,
  approved_by                     uuid NULL,
  approved_at                     timestamptz NULL,
  last_updated_at                 timestamptz NULL,
  last_updated_by                 uuid NULL
);

COMMENT ON TABLE erp_master.material_master IS
'Core identity record for every material. PACE code is system-generated and never changes. FG materials have shade_code, pack_code, external_sku.';

COMMENT ON COLUMN erp_master.material_master.pace_code IS
'System-generated. Format: RM-00001. Never editable after creation. Never reused after deactivation.';

COMMENT ON COLUMN erp_master.material_master.valuation_method IS
'Phase-1: WEIGHTED_AVERAGE only. DIRECT_BATCH_COST is reserved for Phase-2. Application layer must enforce this restriction.';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_mm_pace_code ON erp_master.material_master (pace_code);
CREATE INDEX IF NOT EXISTS idx_mm_external_code ON erp_master.material_master (external_code) WHERE external_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_mm_type ON erp_master.material_master (material_type);
CREATE INDEX IF NOT EXISTS idx_mm_status ON erp_master.material_master (status);
CREATE INDEX IF NOT EXISTS idx_mm_external_sku ON erp_master.material_master (external_sku) WHERE external_sku IS NOT NULL;

COMMIT;
